//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaoZhugong.Models.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionRecord
    {
        public int Seq { get; set; }
        public int ProductSeq { get; set; }
        public int Num { get; set; }
        public int InStock { get; set; }
        public double UnitPrice { get; set; }
        public double TotalPrice { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public int AdministractionFee { get; set; }
        public Nullable<int> SaleTax { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> SaleTime { get; set; }
    }
}
